version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: frontend
    restart: on-failure
    volumes: 
      - ./frontend/src/:/app/src/
    environment: 
      BACKEND_URL: http://backend:7878/api/graphql
    expose: 
      - 3000

  backend:
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: backend
    restart: on-failure
    env_file: 
      - ./db.env
    expose:
      - 7878
    depends_on:
      - db
    ports: 
      - 7878:7878

  proxy:
    build: ./proxy
    container_name: proxy
    restart: on-failure
    ports:
      - 443:443
    secrets:
      - tls-pem
      - tls-key

  db:
    build: ./db
    container_name: db
    restart: on-failure
    env_file: 
      - ./db.env
    volumes: 
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
        
volumes: 
  db-data: {}
  
secrets:
  tls-pem: 
    file: ./proxy/tls/server.pem
  tls-key: 
    file: ./proxy/tls/server.key
    