version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: frontend
    restart: on-failure
    volumes: 
      - ./frontend/src/:/app/src/
      - type: volume
        source: frontend_dist
        target: /app/dist/client
        volume:
          nocopy: false
    environment: 
      BACKEND_URL: http://backend:7878/api/graphql
    expose: 
      - 3000

  backend:
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: backend
    restart: on-failure
    env_file: 
      - ./db.env
      - ./backend.env
    expose:
      - 7878
    ports: 
      - 7878:7878

  proxy:
    build: ./proxy
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes: 
      - frontend_dist:/srv/dist:ro
      - caddy_data:/data
      - caddy_config:/config
    environment: 
      SITE_ADDRESS: localhost

  db:
    build: ./db
    container_name: db
    restart: on-failure
    env_file: 
      - ./db.env
    volumes: 
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
        
volumes: 
  db-data: {}
  frontend_dist: {}
  caddy_data: {}
  caddy_config: {}