version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile-dev
    container_name: frontend
    restart: on-failure
    volumes: 
      - ./frontend/:/app
    environment: 
      BACKEND_URL: http://backend:7878/graphql
    expose: 
      - 3000

  backend:
    build: ./backend
    container_name: backend
    restart: on-failure
    env_file: 
      - ./db.env
    
    expose:
      - 7878
    depends_on:
      - db

  proxy:
    build: ./proxy
    container_name: proxy
    restart: on-failure
    ports:
      - 8080:8080

  db:
    build: ./db
    container_name: db
    restart: on-failure
    env_file: 
      - ./db.env
    volumes: 
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
        
volumes: 
  db-data: {}
    