version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: frontend
    restart: on-failure
    volumes: 
      - ./frontend/src/:/app/src/
      - frontend-dist:/app/dist/client
    environment: 
      BACKEND_URL: http://backend:7878/api/graphql
    expose: 
      - 3000

  backend:
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: backend
    restart: on-failure
    env_file: 
      - ./db.env
      - ./backend.env
    expose:
      - 7878
    ports: 
      - 7878:7878

  proxy:
    build: ./proxy
    container_name: proxy
    restart: on-failure
    ports:
      - 443:8443
    volumes: 
      - frontend-dist:/data/dist
    secrets:
      - tls-cert
      - tls-priv-cert

  db:
    build: ./db
    container_name: db
    restart: on-failure
    env_file: 
      - ./db.env
    volumes: 
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
        
volumes: 
  db-data: {}
  frontend-dist: {}
  
secrets:
  tls-cert: 
    file: ./proxy/tls/server.pem
  tls-priv-cert: 
    file: ./proxy/tls/server.key.pem
    