version: "3.8"
services:
  frontend:
    image: ghcr.io/jedeop/blog_frontend:main
    container_name: frontend
    restart: always
    volumes: 
      - type: volume
        source: frontend_dist
        target: /app/dist/client
        volume:
          nocopy: false
    environment: 
      BACKEND_URL: http://backend:7878/api/graphql
    expose: 
      - 3000

  backend:
    image: ghcr.io/jedeop/blog_backend:main
    container_name: backend
    restart: always
    env_file: 
      - ./db.env
      - ./backend.env
    expose:
      - 7878

  proxy:
    image: ghcr.io/jedeop/blog_proxy:main
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 8443:443
    volumes: 
      - frontend_dist:/srv/dist:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SITE_ADDRESS: blog.jedeop.dev

  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    env_file: 
      - ./db.env
    volumes: 
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
        
volumes: 
  db-data: {}
  frontend_dist: {}
  caddy_data: {}
  caddy_config: {}