version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    environment: 
      BACKEND_URL: http://backend:7878/api/graphql
    expose: 
      - 3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file: 
      - ./db.env
      - ./backend.env
    expose:
      - 7878

  proxy:
    build: ./proxy
    container_name: proxy
    restart: always
    ports:
      - 443:443
    secrets:
      - tls-pem
      - tls-key

  db:
    build: ./db
    container_name: db
    restart: always
    env_file: 
      - ./db.env
    volumes: 
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
        
volumes: 
  db-data: {}
  
secrets:
  tls-pem: 
    file: ./proxy/tls/server.pem
  tls-key: 
    file: ./proxy/tls/server.key
    