version: "3.8"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: jedeop/blog_frontend
    container_name: frontend
    restart: always
    volumes: 
      - type: volume
        source: frontend-dist
        target: /app/dist/client
        volume:
          nocopy: false
    environment: 
      BACKEND_URL: http://backend:7878/api/graphql
    expose: 
      - 3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jedeop/blog_backend
    container_name: backend
    restart: always
    env_file: 
      - ./db.env
      - ./backend.env
    expose:
      - 7878

  proxy:
    build: ./proxy
    image: jedeop/blog_proxy
    container_name: proxy
    restart: always
    ports:
      - 8443:8443
    volumes: 
      - frontend-dist:/data/dist:ro
    secrets:
      - tls-cert
      - tls-priv-cert

  db:
    build: ./db
    image: jedeop/blog_db
    container_name: db
    restart: always
    env_file: 
      - ./db.env
    volumes: 
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
        
volumes: 
  db-data: {}
  frontend-dist: {}
  
secrets:
  tls-cert: 
    file: /etc/letsencrypt/live/blog.jedeop.dev/fullchain.pem
  tls-priv-cert: 
    file: /etc/letsencrypt/live/blog.jedeop.dev/privkey.pem
    
